import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {
  User,
  UserSchema,
  Role,
  RoleSchema,
  Plant,
  PlantSchema,
  Chute,
  ChuteSchema,
  Radar,
  RadarSchema,
  AirBlaster,
  AirBlasterSchema,
  Solenoid,
  SolenoidSchema,
  Compressor,
  CompressorSchema,
  Alert,
  AlertSchema,
  Notification,
  NotificationSchema,
  Telemetry,
  TelemetrySchema,
  GpsLocation,
  GpsLocationSchema,
  HubHealth,
  HubHealthSchema,
  AiPrediction,
  AiPredictionSchema,
  AuditLog,
  AuditLogSchema,
  MaintenanceTicket,
  MaintenanceTicketSchema,
  Assignment,
  AssignmentSchema,
  Organization,
  OrganizationSchema,
  Region,
  RegionSchema,
  Webhook,
  WebhookSchema,
  OpcUaConfig,
  OpcUaConfigSchema,
  BlastOutcome,
  BlastOutcomeSchema,
  ChuteUptimeLog,
  ChuteUptimeLogSchema,
  Incident,
  IncidentSchema,
  CalibrationLog,
  CalibrationLogSchema,
  Session,
  SessionSchema,
  Cell,
  CellSchema,
  Hub,
  HubSchema,
  Command,
  CommandSchema,
  SabConfiguration,
  SabConfigurationSchema,
} from './schemas';

const models = [
  { name: User.name, schema: UserSchema },
  { name: Role.name, schema: RoleSchema },
  { name: Plant.name, schema: PlantSchema },
  { name: Chute.name, schema: ChuteSchema },
  { name: Radar.name, schema: RadarSchema },
  { name: AirBlaster.name, schema: AirBlasterSchema },
  { name: Solenoid.name, schema: SolenoidSchema },
  { name: Compressor.name, schema: CompressorSchema },
  { name: Alert.name, schema: AlertSchema },
  { name: Notification.name, schema: NotificationSchema },
  { name: Telemetry.name, schema: TelemetrySchema },
  { name: GpsLocation.name, schema: GpsLocationSchema },
  { name: HubHealth.name, schema: HubHealthSchema },
  { name: AiPrediction.name, schema: AiPredictionSchema },
  { name: AuditLog.name, schema: AuditLogSchema },
  { name: MaintenanceTicket.name, schema: MaintenanceTicketSchema },
  { name: Assignment.name, schema: AssignmentSchema },
  { name: Organization.name, schema: OrganizationSchema },
  { name: Region.name, schema: RegionSchema },
  { name: Webhook.name, schema: WebhookSchema },
  { name: OpcUaConfig.name, schema: OpcUaConfigSchema },
  { name: BlastOutcome.name, schema: BlastOutcomeSchema },
  { name: ChuteUptimeLog.name, schema: ChuteUptimeLogSchema },
  { name: Incident.name, schema: IncidentSchema },
  { name: CalibrationLog.name, schema: CalibrationLogSchema },
  { name: Session.name, schema: SessionSchema },
  { name: Cell.name, schema: CellSchema },
  { name: Hub.name, schema: HubSchema },
  { name: Command.name, schema: CommandSchema },
  { name: SabConfiguration.name, schema: SabConfigurationSchema },
];

@Module({
  imports: [MongooseModule.forFeature(models)],
  exports: [MongooseModule.forFeature(models)],
})
export class DatabaseModule {}
